[package]
name = "delinquent_food"
version = "0.1.0"
authors = ["Lilith645 <lilith@inet-sys.com>"]
edition = "2018"

[dependencies]
maat_graphics = { path = "./Maat-Graphics/" }
maat_input_handler = { path = "./Maat-InputHandler/" }
cgmath = "0.16.1"
winit = "0.18.0"
rand = "0.6"
